release: 4.0
# tasks - (optional) if no scheduled tasks exists just remove the tasks array
# Testing a change
tasks:
  []
  #   #service - must match the task's container name in the task definition
  # - service: service-x
  #   # cwRuleName - Name of the cloudwatch events rule associated with the ECS service name .
  #   cwRuleName: service-x-cw-rule
  #   # image - New image that you want to deploy.
  #   image: "11111111111.dkr.ecr.us-west-2.amazonaws.com/service-x:2.0.0"

services:
  #service - must match the container name in the task definition
  - service: helloapi
    # clusterName - Name of the ECS cluster where the service exists
    clusterName: definitiv-dev-ecs-cluster
    # serviceName - Name of the ECS service
    serviceName: definitiv-dev-webapp-service
    # image - New image that you want to deploy.
    image: "306931650323.dkr.ecr.ap-southeast-2.amazonaws.com/helloapi:974545ca7bc47a4738726042f536fee968985df5"

    #service - must match the container name in the task definition
  - service: helloworker
    # clusterName - Name of the ECS cluster where the service exists
    clusterName: definitiv-dev-ecs-cluster
    # serviceName - Name of the ECS service
    serviceName: definitiv-dev-background-service-service
    # image - New image that you want to deploy.
    image: "306931650323.dkr.ecr.ap-southeast-2.amazonaws.com/helloworker:974545ca7bc47a4738726042f536fee968985df5"

  #service - must match the container name in the task definition
  - service: redis
    # clusterName - Name of the ECS cluster where the service exists
    clusterName: definitiv-dev-ecs-cluster
    # serviceName - Name of the ECS service
    serviceName: definitiv-dev-redis
    # image - New image that you want to deploy.
    image: "redis:alpine"
